'\" t
.\"     Title: webgrab
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 05/10/2021
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "WEBGRAB" "1" "05/10/2021" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
webgrab \- Capture a snapshot of a web page
.SH "SYNOPSIS"
.sp
\fBwebgrab\fR [\fIOPTIONS\fR] \fIURL\fR \fIOUTFILE\fR [\&...]
.SH "DESCRIPTION"
.sp
\fBwebgrab\fR loads a page from the web (specified by \fIURL\fR) and renders it to a local file\&. The format of the file is determined from its file name\&. Currently, pdf, jpg, png, and many other bitmap file formats are supported in Linux, while only pdf is supported on Mac and Windows\&. This discrepancy will be addressed once Qt\(cqs QWebEngine technology matures\&.
.SH "OPTIONS"
.PP
\fB\-p\fR
.RS 4
Specifies that output should be split into pages\&. (Valid for pdf output only\&.)
.RE
.PP
\fB\-t, \-s, \-m, \-l, \-h\fR
.RS 4
Specifies that output images should be
\fIt\fRiny,
\fIs\fRmall,
\fIm\fRedium,
\fIl\fRarge, or
\fIh\fRuge, which is to say 160, 320, 640, 1280, or 2560 pixels wide\&.
.RE
.SH "BUGS"
.sp
There may be bugs\&. Please contact the author if one bites you\&.
.SH "AUTHOR"
.sp
Daniel Wagenaar <daw@caltech\&.edu>, Division of Biology and Biological Engineering, California Institute of Technology\&. https://www\&.danielwagenaar\&.net\&.
.SH "SEE ALSO"
.sp
\fBnoted\fR(1)
