# Automatically generated by updatesources.sh

HEADERS += \
     AutoNote/AutoNote.h  \
     AutoNote/AN_Pubmed.h  \
     AutoNote/AN_Biblio.h  \

SOURCES += \
     AutoNote/AN_Biblio.cpp  \
     AutoNote/AutoNote.cpp  \
     AutoNote/AN_Pubmed.cpp  \

RESOURCES += \

FORMS += \

