# Automatically generated by updatesources.sh
# on  Mon Feb 11 21:46:08 PST 2013

HEADERS += \
    Book/BookData.H \
    Book/Notebook.H \
    Book/Style.H \
    Book/TOC.H \
    Book/TOCEntry.H \
    Book/TOCFile.H \

SOURCES += \
    Book/BookData.C \
    Book/Notebook.C \
    Book/Style.C \
    Book/TOC.C \
    Book/TOCEntry.C \

RESOURCES += \

