# Automatically generated by updatesources.sh
# on  Fri Feb 8 16:19:18 PST 2013

HEADERS += \
    Book/BookData.H \
    Book/Notebook.H \
    Book/Style.H \
    Book/TOCEntry.H \
    Book/TOCFile.H \
    Book/TOC.H \

SOURCES += \
    Book/BookData.C \
    Book/Notebook.C \
    Book/Style.C \
    Book/TOC.C \
    Book/TOCEntry.C \

RESOURCES += \

