@echo off

rem This is updatesources.bat, a Windows version of updatesources.sh.
rem Make sure to keep the SUBDIRS matched up with the Unix version.

set SUBDIRS=App Book Data File Items Scenes ResourceMagic

cd ..\src

echo # Automatically generated by updatesources.bat > eln.pri
echo. >> eln.pri
echo sourcedirs = ^\>> eln.pri

for %%f in (%SUBDIRS%) do (
  echo     %%f ^\>> eln.pri
  echo # Automatically generated by updatesources.bat > %%f\%%f.pri
  echo. >> %%f\%%f.pri
  echo HEADERS += ^\>> %%f\%%f.pri
  for %%h in (%%f\*.H) do (
    echo     %%h ^\>> %%f\%%f.pri
  )
  echo. >> %%f\%%f.pri

  echo SOURCES += ^\>> %%f\%%f.pri
  for %%c in (%%f\*.cpp) do (
    echo     %%c ^\>> %%f\%%f.pri
  )
  echo. >> %%f\%%f.pri

  echo RESOURCES += ^\>> %%f\%%f.pri
  for %%q in (%%f\*.qrc) do (
    echo     %%q ^\>> %%f\%%f.pri
  )
  echo. >> %%\%%f.pri

  echo FORMS += ^\>> %%f\%%f.pri
  for %%q in (%%f\*.ui) do (
    echo     %%q ^\>> %%f\%%f.pri
  )
  echo. >> %%\%%f.pri
)

echo. >> eln.pri



