# Automatically generated by updatesources.sh
# on  Mon Feb 11 21:46:08 PST 2013

HEADERS += \
    File/BookFile.H \
    File/DataFile.H \
    File/JSONFile.H \
    File/PageFile.H \
    File/ResLoader.H \
    File/SmartURL.H \

SOURCES += \
    File/DataFile.C \
    File/JSONFile.C \
    File/PageFile.C \
    File/ResLoader.C \

RESOURCES += \

