#!/bin/sh

[ -d eln.app ] && rm -r eln.app
make
cp build-webgrab/webgrab eln.app/Contents/MacOS
strip eln.app/Contents/MacOS/*
cp src/App/elnmac.sh eln.app/Contents/MacOS/
chmod a+x eln.app/Contents/MacOS/elnmac.sh
