#!/usr/bin/perl -w

use strict;

# mkrelease - creates a release from a git archive

# Usage: mkrelease [path]
# mkrelease works in the current directory or on the named path

if (@ARGV) {
    chdir shift @ARGV;
}

my $here = `pwd`;
chomp $here;
my @bits = split("/", $here);
my $package = pop @bits;

my $oldvsn;
my $newvsn;
if (-f "changelog") {
    my $headline = `head -n 1 changelog`;
    chomp $headline;
    my ($pkg, $vsn, @junk) = split(" ", $headline);
    die "Junk in changelog headline\n" if @junk || !defined($pkg) || 
	!defined($vsn);
    $oldvsn = $vsn;
    $vsn =~ /^(\d+)\.(\d+)\.(\d+)(-.+)?/ or die "Junk in changelog headline\n";
    $newvsn = "$1.$2." . ($3+1);
} else {
    $newvsn = "0.1.0";
}


