# Automatically generated by updatesources.sh
# on  Fri Feb 8 16:19:18 PST 2013

HEADERS += \
    BookScene/FrontScene.H \
    BookScene/Roman.H \
    BookScene/TOCItem.H \
    BookScene/TOCScene.H \

SOURCES += \
    BookScene/FrontScene.C \
    BookScene/Roman.C \
    BookScene/TOCItem.C \
    BookScene/TOCScene.C \

RESOURCES += \

