# Automatically generated by updatesources.sh
# on  Mon Feb 11 21:46:08 PST 2013

HEADERS += \
    BookScene/FrontScene.H \
    BookScene/Roman.H \
    BookScene/TOCItem.H \
    BookScene/TOCScene.H \

SOURCES += \
    BookScene/FrontScene.C \
    BookScene/Roman.C \
    BookScene/TOCItem.C \
    BookScene/TOCScene.C \

RESOURCES += \

