on: 
  push:
    branches: [ "main" ]

name: Build binaries on linux

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Install requirements for building binary
        run: .github/get-build-requirements
      - name: Build binary
        run: make
      - name: Build .deb
        run: make deb
